### ISSUE TITLE
AttendanceStats ​​can be withdrawn from the database even while in the student account

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#10]
While trying to print the relevant data regarding attendance in the frontend, a 403 error is received due to the student account. In this case, the student cannot see values ​​such as Total Absence Number in the attendance section.

**Comment by Haruncakir** [comment]
Which endpoint did you send the request and also what is the response came from the backend ?

**Comment by Haruncakir** [comment]
I have not relatively finished tests of attendance related endpoints. I will checkout again. If you need the statistics for the student I'll create an endpoint for that. You can tell me if you have any specific request

**Comment by Haruncakir** [comment]
fixed.
