### ISSUE TITLE
UTF-8 problem in PostgreSQL at attendance table - comment column

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#11]
There is a problem with Turkish characters not being supported.

**Comment by Haruncakir** [comment]
UTF-8 supports turkish characters and also the database uses UTF-8 encoding:
```sql
lsm_database=# SELECT datname, pg_encoding_to_char(encoding) AS encoding
lsm_database-# FROM pg_database
lsm_database-# WHERE datname = 'lsm_database';
   datname    | encoding
--------------+----------
 lsm_database | UTF8
(1 row)
```
But made some changes in the filter but I don't know if it works, better try it out.
(Also modify .env file SPRING_DATASOURCE_URL: ...?useUnicode=true&characterEncoding=UTF-8)
