### ISSUE TITLE
student assignment unsubmit error.

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#12]
when ı try to unsubmit an assignment, ı get ERR_BAD_RESPONSE.
AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_RESPONSE"
config
: 
{transitional: {…}, adapter: Array(3), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 500"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: '', status: 500, statusText: 'Internal Server Error', headers: AxiosHeaders, config: {…}, …}
status
: 
500
stack
: 
"AxiosError: Request failed with status code 500\n    at settle (http://localhost:5173/node_modules/.vite/deps/axios.js?v=b64313a4:1230:12)\n    at XMLHttpRequest.onloadend (http://localhost:5173/node_modules/.vite/deps/axios.js?v=b64313a4:1593:7)\n    at Axios.request (http://localhost:5173/node_modules/.vite/deps/axios.js?v=b64313a4:2145:41)\n    at async unsubmitStudentAssignment (http://localhost:5173/src/services/assignmentService.jsx:40:22)\n    at async handleAssignmentUnsubmit (http://localhost:5173/src/components/MainContents/Assignments/StudentAssignments/SingleAssignment/SingleAssignment.jsx?t=1733078832528:49:24)"
[[Prototype]]
: 
Error

 the logs printed to console when ı make the api call given in the txt file.
[aaaaa.txt](https://github.com/user-attachments/files/17970009/aaaaa.txt)

it gives this error
2024-12-01 21:53:52 [http-nio-8080-exec-4] ERROR com.lsm.aspect.LoggingAspect - Exception in method: unsubmitAssignment after 76 ms with error: You can only unsubmit your own assignments

**Comment by Haruncakir** [comment]
fixed.
