### ISSUE TITLE
assignment title uniqueness

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#14]
is there a reason that there can not be more than 1 assignment for a  class with the same name.
If there is not, I believe it is something that should be corrected.

**Comment by Haruncakir** [comment]
The restriction was initially added to ensure uniqueness in assignment names to prevent potential confusion or errors when assigning or searching for assignments but it is NOT mandatorly have to be unique so I will discard the restriction.
