### ISSUE TITLE
duplicate key value problem

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#2]
ı have pulled the latest backend commit  but the issue we are facing with the relogin still continues. Error logs attached.

![image_2024-11-28_204019363](https://github.com/user-attachments/assets/b3ad0d04-9ebd-4277-b280-46da30020e00)
[aaaaa.txt](https://github.com/user-attachments/files/17951141/aaaaa.txt)

**Comment by OnurhanTALAN** [comment]
it throws RateLimitExceededException

**Comment by Haruncakir** [comment]
Tried

**Comment by Haruncakir** [comment]
Updated something. Please try again with the last commit
