### ISSUE TITLE
remove document issue

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#21]
An officer may want to remove a file from an assignment they created. I attempted to achieve this using the uploadDocument endpoint, but it requires a non-null Multipart file. Therefore, I believe we need another endpoint that allows the frontend to remove the document attached to the assignment during its creation.

**Comment by Haruncakir** [comment]
You can manage this on the frontend by ensuring that if a teacher uploads a document but does not finalize the assignment creation (i.e., does not call the endpoint to save the assignment), the document will not be uploaded. This way, you can provide an option for the user to cancel the upload before it is finalized. To delete document for a created assignment, a new endpoint added.
