### ISSUE TITLE
assignmentResponseDTO classID and courseID

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#23]
If an officer wants to make a change to an assignment, they search for the assignment and receive an AssignmentResponseDTO. However, the AssignmentResponseDTO does not include classId and courseId. Since the backend requires the IDs of the class and course when updating the assignment, please add these data fields to the AssignmentResponseDTO as well.

**Comment by Haruncakir** [comment]
Added.
