### ISSUE TITLE
Fetching attendance stats even while in student user

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#25]
Backend should perform fetching attendance stats api call in student user. Because we should show the statistics to student user too. Attachments is added.
![image](https://github.com/user-attachments/assets/e2b61fda-d19c-404b-90ab-f76f545c2f10)

![image](https://github.com/user-attachments/assets/fa5af8d3-46d1-49f2-9a05-9eb7a56c74ff)

**Comment by Haruncakir** [comment]
Fixed.
