### ISSUE TITLE
Filtering Attendance According to Just One Course

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#26]
There should be an API that filtered attendance records belong to a just one course by using startDate and endDate

**Comment by Haruncakir** [comment]
endpoint updated with optional params: (format should be ISO format: yyyy-MM-dd)
```
GET http://localhost:8080/api/v1/attendance/stats/course/1?classId=1&startDate=2024-01-01&endDate=2025-01-01
```
