### ISSUE TITLE
assignment submission without a document

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#30]
when a student tries to submit an assignment without a document uploaded. I get error code 403 with the message given below.
"Error submitting assignment: Cannot invoke "org.springframework.web.multipart.MultipartFile.getOriginalFilename()" because "file" is null"

**Comment by Haruncakir** [comment]
I tested it on Postman using both localhost and the server, but I didn't encounter any issues.
