### ISSUE TITLE
bulk grading

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#31]
when ı try to use the endpoint "bulkGradeAssignment" ı get the error given below eventhough all the students have submitted their assignment
"Some grades failed to be applied: Failed to grade student 6: Can only grade assignments that have been submitted; Failed to grade student 5: Can only grade assignments that have been submitted"

**Comment by Haruncakir** [comment]
When attempting to bulk grade the assignment, you encountered an issue where some students had not submitted their homework, which was restricted by the backend system. This restriction has now been lifted, allowing for smoother grading.
