### ISSUE TITLE
/api/v1/attendance/stats/course/{courseId} returns null recentAttendance

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#36]
{"success":true,"message":"Attendance statistics retrieved successfully","data":[{"studentId":5,"studentName":"Alice","classId":1,"className":"11-A-MF","courseId":1,"courseName":"AYT-Mathematics","attendancePercentage":100.0,"totalClasses":3,"presentCount":2,"absentCount":0,"lateCount":1,"recentAttendance":null},{"studentId":6,"studentName":"Bob","classId":1,"className":"11-A-MF","courseId":1,"courseName":"AYT-Mathematics","attendancePercentage":66.67,"totalClasses":3,"presentCount":2,"absentCount":1,"lateCount":0,"recentAttendance":null}]}

**Comment by Haruncakir** [comment]
Fixed.
