### ISSUE TITLE
getStudentClass

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#37]
when ı make an api call to fetch student's class using the endpoint '/api/v1/classes/student' ı get the error code 500.
the message given below is the response
"Unexpected error: failed to lazily initialize a collection of role: com.lsm.model.entity.ClassEntity.assignments: could not initialize proxy - no Session"

**Comment by Haruncakir** [comment]
Fixed.
