### ISSUE TITLE
document download permission

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#39]
The validatePermission function in the assignmentDocumentService needs to be revised. For example, when an officer wants to grade an assignment, they should be able to download the document uploaded by the student. However, the current endpoint only allows downloading documents uploaded by the creator of the assignment.

**Comment by Haruncakir** [comment]
The issue has been resolved. Additionally, a new endpoint has been implemented for teachers, allowing them to download all student submissions for the assignment in a ZIP format.
