### ISSUE TITLE
getStudentClass

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#42]
"Unexpected error: failed to lazily initialize a collection of role: com.lsm.model.entity.TeacherCourse.classes: could not initialize proxy - no Session"
this is the error message I get when I try to make an api call to the endpoint : '/api/v1/classes'

**Comment by OnurhanTALAN** [comment]
/api/v1/classes/student
actually the endpoint I get this error was '/api/v1/classes/student'. sorry

**Comment by OnurhanTALAN** [comment]
and it still continues

**Comment by Haruncakir** [comment]
It is my stupidity since it wants to get classes from the student but doesn't request any id so how could it know which student!
I changed to endpoint to GET /api/v1/classes/student/{studentId}
