### ISSUE TITLE
attendance conflict

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#45]
![image](https://github.com/user-attachments/assets/582ca173-8cab-407d-a62f-9ae9693cddf6)
I believe there is a conflict between the AttendanceStatDTO and the AttendanceStatus enum. The enum values are ABSENT, PRESENT, and EXCUSED, but AttendanceStatDTO does not include an excusedCount. Instead, it has a lateCount.

**Comment by Haruncakir** [comment]
I added LATE to enum and added excusedCount to DTO
