### ISSUE TITLE
classId problem in AttendanceResponse and AttendanceRequest

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#5]
To get classID we need to send classID.

![image](https://github.com/user-attachments/assets/7934ba66-109a-4e2a-8790-f25f5b221d64)
![image](https://github.com/user-attachments/assets/107b08c9-d9ca-4bdd-9b16-e4a59e5f541b)

**Comment by Haruncakir** [comment]
The class ID field in the request was found to be redundant and has now been removed.
