### ISSUE TITLE
When adding read property, occured problem in delete and update announcement

### ISSUE THREAD

**Issue by Batuminien** [Meliksahcaliskan/Learning-Management-System#52]
When i tried to delete or update a announcement, i gave a response like that:
`{"success":false,"message":"Unexpected error: could not execute statement [ERROR: update or delete on table \"announcements\" violates foreign key constraint \"fko4hw4t3o1109njajdparj6mf4\" on table \"announcement_read_status\"\n  Detail: Key (id)=(8) is still referenced from table \"announcement_read_status\".] [delete from announcements where id=?]; SQL [delete from announcements where id=?]; constraint [fko4hw4t3o1109njajdparj6mf4]","data":null}`

**Comment by Haruncakir** [comment]
I have tried a few times but I didn't get any errors. Can you check validity of your request ?

**Comment by Haruncakir** [comment]
Fixed.
