### ISSUE TITLE
get student assignments

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#6]
when ı make an api call using getStudentAssignments. ı get error code 500 Internal Server Error. ı have attached the the error printed to console, and a screenshot which ı believe where the error occurs.
[aaa.txt](https://github.com/user-attachments/files/17952467/aaa.txt)
![image_2024-11-29_005026879](https://github.com/user-attachments/assets/ce805ce4-a1bc-4567-9322-a7784e807bd8)

**Comment by Haruncakir** [comment]
There was a discrepancy between the expected inputs in the method definition and those provided during the method call. This issue has now been resolved.
