### ISSUE TITLE
getStudentAssignments error

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#7]
ı have merged the backend_dev-v2 commit named "document merged with request" and with the hash code "8ab263c" into my frontedn_dev_v2 branch. it used to give "class not found exception", and now it gives

Exception in method: getAssignmentsByClass after 24 ms with error: failed to lazily initialize a collection of role: com.lsm.model.entity.Assignment.teacherDocuments: could not initialize proxy - no Session        
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.lsm.model.entity.Assignment.teacherDocuments: could not initialize proxy - no Session

above error.
I attached the document which includes printed messages to the console.
[aaa.txt](https://github.com/user-attachments/files/17962116/aaa.txt)

**Comment by Haruncakir** [comment]
Error occurred because the method called was not annotated as transactional. It has been fixed know.
