### ISSUE TITLE
AssignementDTO additional fields

### ISSUE THREAD

**Issue by OnurhanTALAN** [Meliksahcaliskan/Learning-Management-System#9]
in the backend side, if the createAssignment request passes validation check "createAssignmentEntity" is called.

private Assignment createAssignmentEntity(
            AssignmentRequestDTO dto,
            AppUser teacher,
            ClassEntity classEntity,
            Course course) {
        Assignment assignment = new Assignment();
        assignment.setTitle(dto.getTitle());
        assignment.setDescription(dto.getDescription());
        assignment.setDueDate(dto.getDueDate());
        assignment.setAssignedBy(teacher);
        assignment.setClassEntity(classEntity);
        assignment.setCourse(course);
        assignment.setDate(LocalDate.now());
        assignment.setStatus(AssignmentStatus.PENDING);

        return assignment;
    }

as can be seen, it does not set the teacherDocuments. Therefore, eventhough teacher uploads a document it is not saved.

secondly,  AssignmentDTO does not have a data field named "status" which prevents frontend to filter the retrieved assignments.
lastly, there is a inconsistency in creation of an assignment, because AssignmentRequestDTO accepts only one AssignmentDocumentDTO. on the other hand, Assignment class has a data field given below
private Set<AssignmentDocument> teacherDocuments = new HashSet<>();
Since a teacher is able to upload only one document upon the creation of an assignment, there is no need such a set of AssignmentDocuments

**Comment by OnurhanTALAN** [comment]
there should be an api endpoint so that student will be able to submit their assignment with a document if there is one.

**Comment by OnurhanTALAN** [comment]
when an officer wants to create an assignment, the classes that he can assign homeworks should be fetched. therefore, an additional api endpoint should be coded which requires id of the officer. it shouldd return the classes that can assign hws.
additionally same thing should be done for courses. after the officer selects the class he wants to create an assignment, frontend will make an api call with the classID and officerID given. it should return the courses officer can assign for that specific class

**Comment by OnurhanTALAN** [comment]
in active assignments section
![image_2024-11-30_181650026](https://github.com/user-attachments/assets/38079c81-b42e-429c-97c1-35e6815d3f2d)
there are multiple ways an officer query assignments. 
1- he can query all the active assignments of a specific class 
![image_2024-11-30_181812943](https://github.com/user-attachments/assets/76d3a3ae-5d76-4fd4-809c-0697cad6d288)
2- he can query all the active assignments of a specific class and course
![image_2024-11-30_181916698](https://github.com/user-attachments/assets/394e7646-ca11-4b13-84e3-14ca46d29b2b)
3- he can query all the active assignments of a specific class which have an earlier dueDate than given date
![image_2024-11-30_182425333](https://github.com/user-attachments/assets/a27669b0-c861-4307-972f-a5028d04e2d3)
4- he can query all the active assignments which have an earlier duDate than given date

**Comment by Haruncakir** [comment]
> in the backend side, if the createAssignment request passes validation check "createAssignmentEntity" is called.
> 
> private Assignment createAssignmentEntity( AssignmentRequestDTO dto, AppUser teacher, ClassEntity classEntity, Course course) { Assignment assignment = new Assignment(); assignment.setTitle(dto.getTitle()); assignment.setDescription(dto.getDescription()); assignment.setDueDate(dto.getDueDate()); assignment.setAssignedBy(teacher); assignment.setClassEntity(classEntity); assignment.setCourse(course); assignment.setDate(LocalDate.now()); assignment.setStatus(AssignmentStatus.PENDING);
> 
> ```
>     return assignment;
> }
> ```
> 
> as can be seen, it does not set the teacherDocuments. Therefore, eventhough teacher uploads a document it is not saved.
> 
> secondly, AssignmentDTO does not have a data field named "status" which prevents frontend to filter the retrieved assignments. lastly, there is a inconsistency in creation of an assignment, because AssignmentRequestDTO accepts only one AssignmentDocumentDTO. on the other hand, Assignment class has a data field given below private Set teacherDocuments = new HashSet<>(); Since a teacher is able to upload only one document upon the creation of an assignment, there is no need such a set of AssignmentDocuments

status added now and document issue should be fixed!

**Comment by Haruncakir** [comment]
> there should be an api endpoint so that student will be able to submit their assignment with a document if there is one.

added

**Comment by Haruncakir** [comment]
> when an officer wants to create an assignment, the classes that he can assign homeworks should be fetched. therefore, an additional api endpoint should be coded which requires id of the officer. it shouldd return the classes that can assign hws. additionally same thing should be done for courses. after the officer selects the class he wants to create an assignment, frontend will make an api call with the classID and officerID given. it should return the courses officer can assign for that specific class

/api/v1/classes/teacher and /api/v1/classes/student added
endpoints for courses are in progress since it required a change in the DTO.
